### ISSUE TITLE
Audiolab issue with Numpy 1.6.0b2

### ISSUE THREAD

**Issue by excetara2** [cournape/audiolab#6]
David,

I recently upgraded to the newest version of numpy 1.6.0b2 and seems to have issues with scikits.audiolab as I'm getting this error:

/home/bigtyme/Dropbox/Research/Code/AudModel/numpy.pxd in scikits.audiolab.pysndfile._sndfile (scikits/audiolab/pysndfile/_sndfile.c:9632)()

ValueError: numpy.dtype does not appear to be the correct type object

Do you know anything about this?? I will try going back to previous version to see if it corrects this.

**Comment by excetara2** [comment]
I fixed the issue by downloading the newest libsndfile. Then grabbing the version from the git hub to re-install. Not sure where the issue was previously.

**Comment by ibillxia** [comment]
Hi excetara2！

I also come across the same problem on windows. But I can't simply solve it by grabbing the newest version of Audiolab from github.

I'm using Audiolab to draw spectrogram of a wave. But sooner I find that it's not neccessary to import Audiolab, only import matplotlib is enough as there is a function matplotlib.pyplot.specgram() to do it.

As a newbie to Python, I simply commented the 9632 line of _sndfile.c, but the same error occurs still and without any new errors. I‘am looking forward someone would solve this problem sooner or later as I may use this library later. Or maybe I'll solve it sooner.
