### ISSUE TITLE
mp3 support

### ISSUE THREAD

**Issue by endolith** [cournape/audiolab#9]
libsndfile [doesn't support mp3s, and never will](http://www.mega-nerd.com/libsndfile/FAQ.html#Q020).  Can audiolab support mp3s through another library?  

Maybe by merging [this modification](https://github.com/ronw/audiolab/commit/07c3dabfc2178e6ad43bb8762ddd46050e13b86d)?

**Comment by cournape** [comment]
I will not include mp3 support for the same reasons libsndfile does not: mp3 has patenting issues that I am not comfortable dealing with.
